language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_28474bd4aa7a_key -iv $encrypted_28474bd4aa7a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar